Added new features
Scuudu-Labs/Tranzakt-Payment-Gateway-Nodejs-SDK pull request #1
Opened 2024-10-25 09:35 UTC by Stanyke

2024-10-25 12:37 UTC, l-ezeh approved these changes
This seem cute!

2024-10-28 08:18 UTC, Dverybest commented on src/tranzakt.ts
> +  }
```suggestion
  async getInvoice(invoiceId: string): Promise<Invoice> {
    return this.invoiceService.getInvoiceDetails(invoiceId);
  }
```

2024-10-28 08:19 UTC, Dverybest commented on src/tranzakt.ts
> +  }
```suggestion
  async invalidateInvoice(invoiceId: string): Promise<null> {
    return this.invoiceService.invalidateAnInvoice(invoiceId);
  }
```

2024-10-28 08:19 UTC, Dverybest commented on src/tranzakt.ts
> +  }
```suggestion
  async getCollection(collectionId: string): Promise<Collection> {
    return this.collectionService.getCollectionDetails(collectionId);
  }
```

2024-10-28 17:00 UTC, Dverybest requested changes
Your PR name and branch name does not follow our standard please close and redo

2024-10-29 07:42 UTC, closed without merging